package com.portfolio.onlineStore.enums;

public enum Role {
	//BASIC USER
	USER,
	
	//BASIC NON ELEVATED EMPLOYEE
	EMPLOYEE,
	
	//MANAGERIAL ROLE FOR NON ADMINISTRATION BUT ELEVATED EMPLOYEE
	MANAGER,
	
	//HIGHEST ELEVATED PRIVILEGE
	ADMINISTRATOR
}
